on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: curl -s https://codecov.io/env
    - run: >
        export CI_ENV=`bash <(curl -s https://codecov.io/env)` &&
        echo "CI_ENV: $CI_ENV" &&
        docker run --rm --entrypoint '' -v $PWD:/opt $CI_ENV
        --env "QEMU_QMP_CONNECT_ATTEMPTS=10" --env "EXPECTED_QEMU_START_S=20"
        registry.opensuse.org/devel/openqa/containers/openqa_dev
        sh -c 'cd /opt && ./install-patched-qemu.sh && ./autogen.sh &&
        make && make check coverage-codecov VERBOSE=1'

  style:
    runs-on: ubuntu-latest
    name: Run style checks
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: >
        docker run --rm --entrypoint '' -v $PWD:/opt
        registry.opensuse.org/devel/openqa/containers/openqa_dev
        sh -c 'cd /opt && ./autogen.sh && make && make check-style'

